<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sysml" nsURI="http://www.eclipse.org/papyrus/0.7.0/SysML" nsPrefix="SysML">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="OMG SysML V1.1 formal/2008-11-02&#xD;&#xA;Trace instead of Abstraction in SysML specifications."/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EDataType" name="Dummy" instanceClassName="java.lang.String"/>
  <eSubpackages name="modelelements" nsURI="http://www.eclipse.org/papyrus/0.7.0/SysML/ModelElements"
      nsPrefix="ModelElements">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The supplier/target must be an element stereotyped by &lt;&lt;ViewPoint>>&#xD;&#xA;The client/source must be an element stereotyped by &lt;&lt;View>>"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="Conform">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Dependency" ordered="false"
          unique="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Dependency"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="View">
      <eStructuralFeatures xsi:type="ecore:EReference" name="viewPoint" ordered="false"
          unique="false" lowerBound="1" eType="#//modelelements/ViewPoint" changeable="false"
          volatile="true" transient="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Package" ordered="false"
          unique="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Package"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ViewPoint">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
          unique="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="stakeHolders" ordered="false"
          unique="false" upperBound="-1" eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="purpose" ordered="false"
          unique="false" eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="concerns" ordered="false"
          unique="false" upperBound="-1" eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="languages" ordered="false"
          unique="false" upperBound="-1" eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="methods" ordered="false"
          unique="false" upperBound="-1" eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Rationale">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Comment" ordered="false"
          unique="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Comment"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Problem">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Comment" ordered="false"
          unique="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Comment"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="blocks" nsURI="http://www.eclipse.org/papyrus/0.7.0/SysML/Blocks"
      nsPrefix="Blocks">
    <eClassifiers xsi:type="ecore:EClass" name="Block">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isEncapsulated" ordered="false"
          unique="false" eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
          unique="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DistributedProperty">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Property" ordered="false"
          unique="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Property"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Dimension">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_InstanceSpecification"
          ordered="false" unique="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//InstanceSpecification"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Unit">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_InstanceSpecification"
          ordered="false" unique="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//InstanceSpecification"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="dimension" ordered="false"
          unique="false" eType="#//blocks/Dimension"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ValueType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_DataType" ordered="false"
          unique="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//DataType"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="unit" ordered="false"
          unique="false" eType="#//blocks/Unit"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="dimension" ordered="false"
          unique="false" eType="#//blocks/Dimension"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NestedConnectorEnd">
      <eStructuralFeatures xsi:type="ecore:EReference" name="propertyPath" unique="false"
          lowerBound="1" upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Property"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_ConnectorEnd" ordered="false"
          unique="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//ConnectorEnd"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ParticipantProperty">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Property" ordered="false"
          unique="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Property"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="end" ordered="false"
          unique="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Property"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ConnectorProperty">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Property" ordered="false"
          unique="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Property"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="connector" ordered="false"
          unique="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Connector"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BindingConnector">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Connector" ordered="false"
          unique="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Connector"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PropertySpecificType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Classifier" ordered="false"
          unique="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Classifier"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="portandflows" nsURI="http://www.eclipse.org/papyrus/0.7.0/SysML/PortAndFlows"
      nsPrefix="PortAndFlows">
    <eClassifiers xsi:type="ecore:EClass" name="FlowPort">
      <eOperations name="getIcon" ordered="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Image"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Port" ordered="false"
          unique="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Port"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAtomic" ordered="false"
          unique="false" lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//Boolean"
          changeable="false" volatile="true" transient="true" defaultValueLiteral="false"
          derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isConjugated" ordered="false"
          unique="false" eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" ordered="false"
          unique="false" lowerBound="1" eType="#//portandflows/FlowDirection" defaultValueLiteral="inout"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="FlowDirection">
      <eLiterals name="in"/>
      <eLiterals name="out" value="1"/>
      <eLiterals name="inout" value="2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FlowProperty">
      <eOperations name="getIcon" ordered="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Image"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Property" ordered="false"
          unique="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Property"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" ordered="false"
          unique="false" lowerBound="1" eType="#//portandflows/FlowDirection" defaultValueLiteral="inout"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FlowSpecification">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Interface" ordered="false"
          unique="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Interface"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ItemFlow">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_InformationFlow"
          ordered="false" unique="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//InformationFlow"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="itemProperty" ordered="false"
          unique="false" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Property"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="constraints" nsURI="http://www.eclipse.org/papyrus/0.7.0/SysML/Constraints"
      nsPrefix="Constraints">
    <eClassifiers xsi:type="ecore:EClass" name="ConstraintBlock" eSuperTypes="#//blocks/Block"/>
    <eClassifiers xsi:type="ecore:EClass" name="ConstraintProperty">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Property" ordered="false"
          unique="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Property"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="activities" nsURI="http://www.eclipse.org/papyrus/0.7.0/SysML/Activities"
      nsPrefix="Activities">
    <eClassifiers xsi:type="ecore:EClass" name="Optional">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Parameter" ordered="false"
          unique="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Parameter"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Rate">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Parameter" ordered="false"
          unique="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Parameter"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_ActivityEdge" ordered="false"
          unique="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//ActivityEdge"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rate" ordered="false"
          unique="false" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//InstanceSpecification"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Probability">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_ActivityEdge" ordered="false"
          unique="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//ActivityEdge"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_ParameterSet" ordered="false"
          unique="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//ParameterSet"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="probability" ordered="false"
          unique="false" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//ValueSpecification"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Continuous" eSuperTypes="#//activities/Rate"/>
    <eClassifiers xsi:type="ecore:EClass" name="Discrete" eSuperTypes="#//activities/Rate"/>
    <eClassifiers xsi:type="ecore:EClass" name="ControlOperator">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Operation" ordered="false"
          unique="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Operation"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Behavior" ordered="false"
          unique="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Behavior"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NoBuffer">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_ObjectNode" ordered="false"
          unique="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//ObjectNode"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Overwrite">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_ObjectNode" ordered="false"
          unique="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//ObjectNode"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="allocations" nsURI="http://www.eclipse.org/papyrus/0.7.0/SysML/Allocations"
      nsPrefix="Allocations">
    <eClassifiers xsi:type="ecore:EClass" name="Allocate">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Abstraction" ordered="false"
          unique="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Abstraction"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Allocated">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_NamedElement" ordered="false"
          unique="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//NamedElement"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="allocatedFrom" ordered="false"
          unique="false" upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//NamedElement"
          changeable="false" volatile="true" transient="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="allocatedTo" ordered="false"
          unique="false" upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//NamedElement"
          changeable="false" volatile="true" transient="true" derived="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AllocateActivityPartition">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_ActivityPartition"
          ordered="false" unique="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//ActivityPartition"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="requirements" nsURI="http://www.eclipse.org/papyrus/0.7.0/SysML/Requirements"
      nsPrefix="Requirements">
    <eClassifiers xsi:type="ecore:EClass" name="DeriveReqt" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml.profile.standard/model/Standard.ecore#//Trace"/>
    <eClassifiers xsi:type="ecore:EClass" name="Verify" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml.profile.standard/model/Standard.ecore#//Trace"/>
    <eClassifiers xsi:type="ecore:EClass" name="Copy" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml.profile.standard/model/Standard.ecore#//Trace"/>
    <eClassifiers xsi:type="ecore:EClass" name="Satisfy" eSuperTypes="platform:/plugin/org.eclipse.uml2.uml.profile.standard/model/Standard.ecore#//Trace"/>
    <eClassifiers xsi:type="ecore:EClass" name="TestCase">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Behavior" ordered="false"
          unique="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Behavior"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Operation" ordered="false"
          unique="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Operation"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="verifies" ordered="false"
          unique="false" upperBound="-1" eType="#//requirements/Requirement" changeable="false"
          volatile="true" transient="true" derived="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Requirement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" ordered="false"
          unique="false" lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" ordered="false" unique="false"
          lowerBound="1" eType="ecore:EDataType platform:/plugin/org.eclipse.uml2.types/model/Types.ecore#//String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="derived" ordered="false"
          unique="false" upperBound="-1" eType="#//requirements/Requirement" changeable="false"
          volatile="true" transient="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="derivedFrom" ordered="false"
          unique="false" upperBound="-1" eType="#//requirements/Requirement" changeable="false"
          volatile="true" transient="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="satisfiedBy" ordered="false"
          unique="false" upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//NamedElement"
          changeable="false" volatile="true" transient="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="refinedBy" ordered="false"
          unique="false" upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//NamedElement"
          changeable="false" volatile="true" transient="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="tracedTo" ordered="false"
          unique="false" upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//NamedElement"
          changeable="false" volatile="true" transient="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="verifiedBy" ordered="false"
          unique="false" upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//NamedElement"
          changeable="false" volatile="true" transient="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="master" ordered="false"
          unique="false" eType="#//requirements/Requirement" changeable="false" volatile="true"
          transient="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
          unique="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RequirementRelated">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_NamedElement" ordered="false"
          unique="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.uml2.uml/model/UML.ecore#//NamedElement"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="tracedFrom" ordered="false"
          unique="false" upperBound="-1" eType="#//requirements/Requirement" changeable="false"
          volatile="true" transient="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="satisfies" ordered="false"
          unique="false" upperBound="-1" eType="#//requirements/Requirement" changeable="false"
          volatile="true" transient="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="refines" ordered="false"
          unique="false" upperBound="-1" eType="#//requirements/Requirement" changeable="false"
          volatile="true" transient="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="verifies" ordered="false"
          unique="false" upperBound="-1" eType="#//requirements/Requirement" changeable="false"
          volatile="true" transient="true" derived="true"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="interactions" nsURI="http://www.eclipse.org/papyrus/0.7.0/SysML/Interactions"
      nsPrefix="Interactions">
    <eClassifiers xsi:type="ecore:EDataType" name="Dummy" instanceClassName="java.lang.String"/>
  </eSubpackages>
  <eSubpackages name="statemachines" nsURI="http://www.eclipse.org/papyrus/0.7.0/SysML/StateMachines"
      nsPrefix="StateMachines">
    <eClassifiers xsi:type="ecore:EDataType" name="Dummy" instanceClassName="java.lang.String"/>
  </eSubpackages>
  <eSubpackages name="usecases" nsURI="http://www.eclipse.org/papyrus/0.7.0/SysML/UseCases"
      nsPrefix="UseCases">
    <eClassifiers xsi:type="ecore:EDataType" name="Dummy" instanceClassName="java.lang.String"/>
  </eSubpackages>
</ecore:EPackage>
